//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        public int IdEquipo { get; set; }
        public string NombreEquipo { get; set; }
        public Nullable<int> IdTecnico { get; set; }
        public string FechaFundacion { get; set; }
    
        public virtual Tecnico Tecnico { get; set; }
    }
}
