//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        public Tecnico()
        {
            this.Equipo = new HashSet<Equipo>();
        }
    
        public int IdTecnico { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
    
        public virtual ICollection<Equipo> Equipo { get; set; }
    }
}
